name: Mobile Release

on:
  #workflow_dispatch:
  push:
    branches:
      - main

jobs:

  call-validate-config:
    uses: edilsonspecht/reusable-workflows/.github/workflows/validate-release.yml@main
    with:
      environment: DEV
      application: mobile-app-demo

  call-security:
    needs: call-validate-config
    uses: edilsonspecht/reusable-workflows/.github/workflows/security-scan.yml@main

    with:
      fortify-enabled: true
      checkmarx-enabled: true
      mend-enabled: true

  call-build:
    needs: call-security
    uses: edilsonspecht/reusable-workflows/.github/workflows/build-mobile.yml@main

  call-release-hom:
    needs: call-build
    uses: edilsonspecht/reusable-workflows/.github/workflows/release-hom.yml@main

  call-release-prod:
    needs: call-release-hom
    uses: edilsonspecht/reusable-workflows/.github/workflows/release-prod.yml@main
